// <auto-generated />
using System;
using ClubEFLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClubEFLibrary.Migrations
{
    [DbContext(typeof(ClubContext))]
    [Migration("20200518171024_fixedTransfer2")]
    partial class fixedTransfer2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("libraryClubEF.Speler", b =>
                {
                    b.Property<int>("SpelerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RugNummer")
                        .HasColumnType("int");

                    b.Property<string>("SpelerNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamStamNummer")
                        .HasColumnType("int");

                    b.Property<int>("Waarde")
                        .HasColumnType("int");

                    b.HasKey("SpelerId");

                    b.HasIndex("TeamStamNummer");

                    b.ToTable("Spelers");
                });

            modelBuilder.Entity("libraryClubEF.Team", b =>
                {
                    b.Property<int>("StamNummer")
                        .HasColumnType("int");

                    b.Property<string>("TeamBijnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StamNummer");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("libraryClubEF.Transfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SpelerId")
                        .HasColumnType("int");

                    b.Property<decimal>("TransferPrijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("nieuwTeamStamNummer")
                        .HasColumnType("int");

                    b.Property<int?>("oudTeamStamNummer")
                        .HasColumnType("int");

                    b.HasKey("TransferId");

                    b.HasIndex("SpelerId");

                    b.HasIndex("nieuwTeamStamNummer");

                    b.HasIndex("oudTeamStamNummer");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("libraryClubEF.Speler", b =>
                {
                    b.HasOne("libraryClubEF.Team", null)
                        .WithMany("spelers")
                        .HasForeignKey("TeamStamNummer");
                });

            modelBuilder.Entity("libraryClubEF.Transfer", b =>
                {
                    b.HasOne("libraryClubEF.Speler", "Speler")
                        .WithMany()
                        .HasForeignKey("SpelerId");

                    b.HasOne("libraryClubEF.Team", "nieuwTeam")
                        .WithMany()
                        .HasForeignKey("nieuwTeamStamNummer");

                    b.HasOne("libraryClubEF.Team", "oudTeam")
                        .WithMany()
                        .HasForeignKey("oudTeamStamNummer");
                });
#pragma warning restore 612, 618
        }
    }
}
